
FROM node:16-alpine

RUN npm install -g nodemon

RUN mkdir -p /app

WORKDIR /app

# Copiamos solo los archivos necesarios para instalar dependencias
COPY package*.json ./

RUN npm install
# Asegúrate de NO hacer COPY . . después del npm install si estás usando volumes, o se sobreescribirá el contenido al levantar el contenedor.
COPY . .

# EXPOSE 4000

CMD ["nodemon", "index.js"]
