export const estadosMexico = [
    { nombre: 'Aguascalientes', abreviatura: 'AS' },
    { nombre: 'Baja California', abreviatura: 'BC' },
    { nombre: 'Baja California Sur', abreviatura: 'BS' },
    { nombre: 'Campeche', abreviatura: 'CC' },
    { nombre: 'Chiapas', abreviatura: 'CS' },
    { nombre: 'Chihuahua', abreviatura: 'CH' },
    { nombre: 'Ciudad de México', abreviatura: 'DF' },
    { nombre: 'Coahuila', abreviatura: 'CL' },
    { nombre: 'Colima', abreviatura: 'CM' },
    { nombre: 'Durango', abreviatura: 'DG' },
    { nombre: 'Guanajuato', abreviatura: 'GT' },
    { nombre: 'Guerrero', abreviatura: 'GR' },
    { nombre: 'Hidalgo', abreviatura: 'HG' },
    { nombre: 'Jalisco', abreviatura: 'JC' },
    { nombre: 'México', abreviatura: 'MC' },
    { nombre: 'Michoacán', abreviatura: 'MN' },
    { nombre: 'Morelos', abreviatura: 'MS' },
    { nombre: 'Nayarit', abreviatura: 'NT' },
    { nombre: 'Nuevo León', abreviatura: 'NL' },
    { nombre: 'Oaxaca', abreviatura: 'OC' },
    { nombre: 'Puebla', abreviatura: 'PL' },
    { nombre: 'Querétaro', abreviatura: 'QO' },
    { nombre: 'Quintana Roo', abreviatura: 'QR' },
    { nombre: 'San Luis Potosí', abreviatura: 'SP' },
    { nombre: 'Sinaloa', abreviatura: 'SL' },
    { nombre: 'Sonora', abreviatura: 'SR' },
    { nombre: 'Tabasco', abreviatura: 'TC' },
    { nombre: 'Tamaulipas', abreviatura: 'TS' },
    { nombre: 'Tlaxcala', abreviatura: 'TL' },
    { nombre: 'Veracruz', abreviatura: 'VZ' },
    { nombre: 'Yucatán', abreviatura: 'YN' },
    { nombre: 'Zacatecas', abreviatura: 'ZS' },
    { nombre: 'Nacido en el extranjero', abreviatura: 'NE' },
  ];